### ISSUE TITLE
Enhanced Configurations & UI/UX

### ISSUE THREAD

**Issue by QBlockQ** [kumulynja/ldk_node_flutter_demo#25]
Thanks for this repo.  We've made major changes on the backend1 and also ui/ux for a better user experience.  If you're interested, let's know to set up a meeting and share with you this version.  Thanks

**Comment by kumulynja** [comment]
Hi, thanks for the effort, this code definitely can use a lot of improvements, but it was just done to get familiar with the LDK node package's API and not as a production app.
I wanted to share my process openly so it could also be useful to others. It would be very nice if you could do the same and just contribute your improvements through a Pull Request. This way everyone can learn from your version too.
